command = '__YNH_APP_PATH__/venv/bin/gunicorn'
pythonpath = '__YNH_APP_PATH__'
workers = 3
user = '__YNH_APP_NAME__'
# bind = 'unix:__YNH_APP_PATH__/sock'
bind = '127.0.0.1:8000'
pid = '/run/gunicorn/__YNH_APP_NAME__-pid'
errorlog = '/var/log/__YNH_APP_NAME__/error.log'
accesslog = '/var/log/__YNH_APP_NAME__/access.log'
access_log_format = '%({X-Real-IP}i)s %({X-Forwarded-For}i)s %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
loglevel = 'warning'
capture_output = True
