#!/bin/bash
set -u

# Source YunoHost helpers
source /usr/share/yunohost/helpers
source _future.sh

# Retrieve app settings
readonly app=$YNH_APP_INSTANCE_NAME
readonly domain=$(ynh_app_setting_get "$app" domain)
readonly app_system_name=$(ynh_app_setting_get "$app" system_name)
readonly final_path=/var/www/$app
echo "app:"$app "domain:"$domain "app_system_name:"$app_system_name "final_path:"$final_path

# Remove dependencies
ynh_remove_app_dependencies

# Remove nginx configuration file
ynh_secure_remove /etc/nginx/conf.d/$domain.d/$app.conf

# Remove services
yunohost service stop $app
killall $app
yunohost service remove $app
ynh_secure_remove /etc/systemd/system/$app.service
systemctl daemon-reload

# Remove sources
ynh_secure_remove $final_path

# Delete system user
ynh_system_user_delete $app_system_name 

# Reload nginx service
service nginx reload
